# Vectors and Matrices in Numpy - Lab

## Introduction

In this lab, you'll solve some simple matrix creation and manipulation exercises based on what you've learned so far in this section. The key takeaway here is to be able to understand how to use indexing with matrices and vectors while applying some basic operations.

## Objectives
You will be able to:
* Define vectors and matrices in NumPy
* Check the shape of vectors and matrices
* Access and manipulate individual scalar components of a matrix. 

## 1. Define two arrays $A$  with shape $ (4 \times 2)$ and $B$ with shape $(2 \times 3)$ 
So    $A =    
  \left[ {\begin{array}{cc}
   1402 & 191 \\
   1371 &  821\\
   949 &  1437 \\
   147 & 1448 \\
  \end{array} }\right]
$
and
$
B =    
  \left[ {\begin{array}{ccc}
   1 & 2 & 3 \\
   4 & 5 & 6\\
  \end{array} }\right]
$

In [1]:
# Code Here
import numpy as np
A = np.array([[1402, 191], [1371, 821], [949, 1437], [147, 1448]])
B = np.array([[1, 2, 3], [4, 5, 6]])
print ('A=\n', A)
print ('B=\n', B)

A=
 [[1402  191]
 [1371  821]
 [ 949 1437]
 [ 147 1448]]
B=
 [[1 2 3]
 [4 5 6]]


## 2. Print the dimensions of $A$ and $B$ 

In [2]:
# Code Here
A.shape, B.shape

((4, 2), (2, 3))

## 3. Print some of the elements from $A$: 
* first row and first column
* first row and second column
* third row and second column
* fourth row and first column

In [4]:
# Code Here

print(A[0,0])
print(A[0,1])
print(A[2,1])
print(A[3,0])

1402
191
1437
147


## 4. Write a routine to populate a matrix with random data
* Create an $(3 \times 3)$ Numpy array with all zeros (use `np.zeros()`)
* Access each location $(i,j)$ of this matrix and fill in random values between the range 1 and 10. 

In [16]:
# Code Here (due to random data , your output might be different)
import random
C = np.zeros((3,3))
for x in range(0,C.shape[0]):  # Shape (3,3)
    print(f"row: {x}")
    for y in range(0,C.shape[1]):
        print(f"col -- {y}")
        C[x][y] = random.randrange(1, 10)
        print(C[x][y])
print ('\nafter random data:\n',C)


row: 0
col -- 0
5.0
col -- 1
1.0
col -- 2
3.0
row: 1
col -- 0
2.0
col -- 1
1.0
col -- 2
1.0
row: 2
col -- 0
9.0
col -- 1
7.0
col -- 2
4.0

after random data:
 [[5. 1. 3.]
 [2. 1. 1.]
 [9. 7. 4.]]


## 5. Turn the above routine into a function
* Create two $(4 \times 4)$ zero-valued matrices and fill with random data using the function
* Add the matrices together in numpy 
* Show the results

In [26]:
# Code Here (due to random data , your output might be different)
def matrix_zero(matrix):
    for x in range(0,matrix.shape[0]):  # Shape (row,col)
        for y in range(0,matrix.shape[1]):
            matrix[x][y] = random.randrange(1, 10)
            #print(matrix[x][y])
    print (f'\nMatrix:\n',matrix)
    return matrix

M1 = np.zeros((4,4))
M2 = np.zeros((4,4)) 

M1_filled = matrix_zero(M1)
M2_filled = matrix_zero(M2)
out = M1_filled + M2_filled

print ('Final output\n\n', out)


Matrix:
 [[4. 9. 7. 3.]
 [3. 4. 5. 8.]
 [8. 8. 8. 5.]
 [6. 2. 1. 6.]]

Matrix:
 [[8. 1. 6. 9.]
 [8. 7. 8. 5.]
 [7. 9. 6. 2.]
 [5. 2. 9. 9.]]
Final output

 [[12. 10. 13. 12.]
 [11. 11. 13. 13.]
 [15. 17. 14.  7.]
 [11.  4. 10. 15.]]


## Summary 

In this lab, we saw how to create and manipulate vectors and matrices in numpy. We shall now move forward to learning more complex operations including dot products and inverses. 